"""empty message

Revision ID: 530cf6e86254
Revises: 
Create Date: 2020-10-18 15:11:13.107744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '530cf6e86254'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('content')
    # ### end Alembic commands ###
